#!/usr/bin/env node

/**
 * Build-time secret and config injection for Lambda@Edge.
 *
 * Fetches secrets from AWS Secrets Manager, downloads Google's JWKS
 * for JWT signature verification, and writes config.mjs with real values.
 * Run this before `sam build`.
 *
 * Lambda@Edge cannot use environment variables or access AWS services
 * at runtime in Viewer Request (5s timeout + cold start constraints),
 * so secrets and signing keys are baked into the deployment package.
 *
 * Usage:
 *   node buildspec.mjs                    # uses default secret names
 *   AWS_REGION=us-east-1 node buildspec.mjs
 *
 * Required AWS permissions:
 *   secretsmanager:GetSecretValue on kittycam/*
 */

import { execSync } from "node:child_process";
import https from "node:https";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONFIG_PATH = join(__dirname, "src", "auth", "config.mjs");
const REGION = process.env.AWS_REGION || "us-east-1";

const GOOGLE_JWKS_URL = "https://www.googleapis.com/oauth2/v3/certs";

const SECRET_NAMES = {
  oauth: "kittycam/oauth",
  cookieKey: "kittycam/cookie-key",
  allowedEmails: "kittycam/allowed-emails",
};

function getSecret(secretId) {
  const cmd = `aws secretsmanager get-secret-value --secret-id "${secretId}" --region "${REGION}" --query SecretString --output text`;
  const result = execSync(cmd, { encoding: "utf8" }).trim();
  return JSON.parse(result);
}

/**
 * Fetch Google's JWKS (JSON Web Key Set) for JWT signature verification.
 * These keys rotate roughly every 6 hours but remain valid for weeks.
 * Baking them at build time is safe — a redeployment refreshes them.
 */
function fetchGoogleJWKS() {
  return new Promise((resolve, reject) => {
    https.get(GOOGLE_JWKS_URL, { timeout: 10000 }, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`Failed to fetch Google JWKS: HTTP ${res.statusCode}`));
        return;
      }
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => {
        try {
          const jwks = JSON.parse(data);
          if (!jwks.keys || !Array.isArray(jwks.keys) || jwks.keys.length === 0) {
            reject(new Error("Google JWKS response has no keys"));
            return;
          }
          // Only keep the fields we need (kid, n, e) to minimize deployment size
          const keys = jwks.keys
            .filter((k) => k.kty === "RSA" && k.use === "sig" && k.alg === "RS256")
            .map(({ kid, n, e }) => ({ kid, n, e }));
          if (keys.length === 0) {
            reject(new Error("No RS256 signing keys found in Google JWKS"));
            return;
          }
          resolve(keys);
        } catch (err) {
          reject(new Error(`Failed to parse Google JWKS: ${err.message}`));
        }
      });
    }).on("error", reject);
  });
}

async function main() {
  console.log("Fetching secrets from AWS Secrets Manager...");

  const oauth = getSecret(SECRET_NAMES.oauth);
  const cookieKey = getSecret(SECRET_NAMES.cookieKey);
  const allowedEmails = getSecret(SECRET_NAMES.allowedEmails);

  if (!oauth.client_id || !oauth.client_secret) {
    throw new Error(`Secret ${SECRET_NAMES.oauth} must contain client_id and client_secret`);
  }
  if (!cookieKey.encryption_key) {
    throw new Error(`Secret ${SECRET_NAMES.cookieKey} must contain encryption_key`);
  }
  if (!Array.isArray(allowedEmails.emails) || allowedEmails.emails.length === 0) {
    throw new Error(`Secret ${SECRET_NAMES.allowedEmails} must contain a non-empty emails array`);
  }

  // Previous keys for cookie rotation — allows graceful key migration
  // without invalidating active sessions. Optional field.
  const previousKeys = cookieKey.previous_keys || [];
  if (!Array.isArray(previousKeys)) {
    throw new Error(`Secret ${SECRET_NAMES.cookieKey} previous_keys must be an array if present`);
  }

  console.log("Fetching Google JWKS for JWT signature verification...");
  const googleJwks = await fetchGoogleJWKS();
  console.log(`  Found ${googleJwks.length} RS256 signing keys`);

  const emails = allowedEmails.emails.map((e) => e.toLowerCase().trim());

  const configContent = `// Auto-generated by buildspec.mjs — DO NOT EDIT OR COMMIT
// Generated at: ${new Date().toISOString()}

export const OAUTH_CLIENT_ID = ${JSON.stringify(oauth.client_id)};
export const OAUTH_CLIENT_SECRET = ${JSON.stringify(oauth.client_secret)};

// Current encryption key — used for encrypting new cookies
export const COOKIE_ENCRYPTION_KEY = Buffer.from(${JSON.stringify(cookieKey.encryption_key)}, "base64");

// Previous keys — used for decrypting cookies encrypted with older keys
// during key rotation. Allows active sessions to remain valid.
export const COOKIE_ENCRYPTION_KEYS_PREVIOUS = ${JSON.stringify(previousKeys)}.map((k) => Buffer.from(k, "base64"));

export const ALLOWED_EMAILS = ${JSON.stringify(emails)};

// Google's JWKS for id_token RSA signature verification.
// These rotate roughly every 6 hours — a redeployment refreshes them.
// If signature verification fails due to stale keys, the user simply
// re-authenticates (the cookie flow still works, just this one token is rejected).
export const GOOGLE_JWKS = ${JSON.stringify(googleJwks)};

export const DOMAIN = "kittycam.chrispivonka.com";
`;

  writeFileSync(CONFIG_PATH, configContent, "utf8");
  console.log(`Config written to ${CONFIG_PATH}`);
  console.log(`  OAuth client ID: ${oauth.client_id.substring(0, 12)}...`);
  console.log(`  Allowed emails: ${emails.length}`);
  console.log(`  Cookie key: [${cookieKey.encryption_key.length} chars]`);
  console.log(`  Previous cookie keys: ${previousKeys.length}`);
  console.log(`  Google JWKS kids: ${googleJwks.map((k) => k.kid).join(", ")}`);
}

main();
